In [2]:
# A Python library is a collection of functions that provides reusable code for specific tasks.These libraries simplify complex operations 
# by offering pre-written functions that can be used across different programs.

In [3]:
# Numpy provides package for scientific computation it provides efficient operations on hogenous data whereas list lists are ordered and changable collections in python,
# Numpy contains only (homogenous) data whereas list can hold different ypes of data(heterogeneous) 
# Numpy  elements are stored contiguously in memory whereas list do not store data in a contiguous manner
# Numpy arrays are optimized for efficient computation and faster whereas list are not much efficient computations and slower.

In [4]:
import numpy as np

In [5]:
arr = np.array([[1, 2, 3, 4] , [5, 6, 7, 8] , [9, 10, 11, 12]])

In [6]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [7]:
arr.shape

(3, 4)

In [8]:
arr.size

12

In [9]:
arr.ndim

2

In [10]:
arr[0]

array([1, 2, 3, 4])

In [11]:
arr[2,3]

12

In [12]:
arr[ : , 1::2]

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [13]:
import random as random

In [14]:
arr1 = np.random.randint(0,1 , (3,3))
arr1

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [15]:
np.random.rand(3,3) # the numpy rand function generates a 3x3 array of random values

array([[0.8248821 , 0.12913126, 0.72552614],
       [0.78331551, 0.47503387, 0.5132994 ],
       [0.3018495 , 0.12184269, 0.11166755]])

In [16]:
np.random.randn(3,3) # the numpy rand function generates a 3x3 array of random normal  values

array([[-2.43051993,  0.84454053,  1.39563476],
       [-1.23374842, -0.55267895, -0.93641452],
       [ 0.51789628, -1.5075595 ,  0.57899225]])

In [17]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [18]:
np.expand_dims(arr, axis = 0)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [19]:
arr.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [20]:
Matrix_a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
Matrix_b = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [21]:
Matrix_a * Matrix_b

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [22]:
a = np.random.randint(1,10, (3,3))
b = np.random.randint(1,10, (3,3))
# matrix multiplication
a @ b

array([[63, 81, 66],
       [78, 42, 68],
       [70, 41, 62]])

In [23]:
Matrix_a + Matrix_b

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [24]:
Matrix_a - Matrix_b

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [25]:
Matrix_a / Matrix_b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
# the byteswap() function is used to swap the byte order of an array

In [27]:
#The np.linalg.inv() function in NumPy is used to compute the matrix inverse.
# It is significant in solving linear equations

In [28]:
# the reshape function reshapes the shape of array with increasing the size of an array but can increrase or decrease the dimension of an array
# the reshape functions is used just by calling the function name (arr.reshape)

In [29]:
# Broadcasting means adding a same number/integer to an entire array.